services:
  api:
    build:
      context: .
      dockerfile: ./prueba_tecnica/Dockerfile
    ports:
      - 8088:8080
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=awadeuwu
      - POSTGRES_DB=prueba
      - POSTGRES_USER=usuario
    ports:
      - 5435:5432
    volumes:
      - pg_vol:/var/lib/postgresql/data
      - ./seguridad.sql:/docker-entrypoint-initdb.d/seguridad.sql
volumes:
  pg_vol:

